### ISSUE TITLE
Local copy in assets directory, and _resampled directories?

### ISSUE THREAD

**Issue by PixelDog** [fspringveldt/ss-easy-s3#1]
This module is excellent! Just two simple questions:
1) I noticed that after a picture is transferred to S3, it remains in the local assets directory. Is there a configuration option to delete the image from the sites assets folder, and just use the Asset from S3? Looking, it seems like I might need to ad another method for that?
2) I noticed the configuration skips the _resampled directories. Is that a personal preference, or is it better to do that?

**Comment by fspringveldt** [comment]
Hi PixelDog. Glad you found it useful. In terms of answering your questions:
1. Correct, you might have to add another method (would be great if it's configurable) to delete the file after it's added to S3, then avoiding having it hit the onAfterDelete(). Shouldn't prove to big a challenge though. Mind submitting a PR for this?
2. I skipped _resampled by default on the project I was working on at the time, so no personal preference and just based on client specs. Can easily be excluded from the config.

Any changes and/or recommendations are welcome :)

**Comment by PixelDog** [comment]
Great information thank you. Yes, I can submit a PR. I'll be working on it!

**Comment by fspringveldt** [comment]
Hi PixelDog. I've just added this functionality and updated the .README with how to implement it :) Let me know how it goes.
