### ISSUE TITLE
Class 'Aws\S3\S3Client' not found in S3Facade.php

### ISSUE THREAD

**Issue by claire-ee** [fspringveldt/ss-easy-s3#3]
Am getting this Fatal error when trying to run the Task migrate theme to S3

`Fatal error: Class 'Aws\S3\S3Client' not found in /ss-easy-s3/code/classes/S3Facade.php on line 55`

Also when trying to upload an image through an uploadfield i get

`SyntaxError: Unexpected token < in JSON at position 0`

I'm thinking I have the aws folder in the wrong place. Please confirm it should be in root/vendor. So for example root/vendor/aws/aws-sdk-php/src/S3/S3Client.php

**Comment by fspringveldt** [comment]
Hey @claire-ee. `root/vendor` should be fine yes.

Please paste the results of your `composer show` from your project root.

**Comment by experienceengine** [comment]
I didn't install via composer, just zip. I found the issue. I had downloaded the latest version of AWS and not the required version, plus  hadn't required the autoloader for aws. All working now

**Comment by claire-ee** [comment]
I didn't install via composer, just zip. I found the issue. I had downloaded the latest version of AWS and not the required version, plus hadn't required the autoloader for aws. All working now

**Comment by fspringveldt** [comment]
Aah yes. Okay glad you got it sorted.
