### ISSUE TITLE
Doesn't work using 'http' such as local project running on localhost with port 80

### ISSUE THREAD

**Issue by agil3st** [fspringveldt/ss-easy-s3#9]
I was wondering if i can do the upload test in my local project. But unfortunately, i got following exception when i debug `S3Exception` in catch section under `code/extentions/S3FileExtension.php` file

`Error executing "PutObject" on "https://bucket-name.s3.region-name.amazonaws.com/assets/Uploads/fileName.png"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Is there any config to disable SSL validation, bypassing it or something?

**Comment by agil3st** [comment]
You may refer to this [discussion](https://stackoverflow.com/questions/24620393/aws-ssl-security-error-curl-60-ssl-certificate-prob-unable-to-get-local?answertab=votes#tab-top). I found it and someone said it needs _Certificate_ file with `.pem` extension and need additional config inside `setupS3Client()` and `setupCloudFrontClient()` in `code/classes/S3Facade.php` file

**Comment by agil3st** [comment]
Never mind. I solve this issue by changing scheme to http and add certificate file. Here goes my magic 4 steps :v

1. Download [certificate](https://curl.haxx.se/ca/cacert.pem) file
2. Copy it inside `ss-easy-s3/` root directory (assuming `ss-easy-s3` folder is inside project root directory)
3. Add some additional config below inside the config `array()` in `setupS3Client()` and `setupCloudFrontClient()` method in `code/classes/S3Facade.php` file

        $array = array(
            'version' => ...,
            'region' => ...,
            'credentials' => ...,
            // add these lines
            'scheme'  => 'http',
            'http'    => [
                'verify' => '../ss-easy-s3/cacert.pem'
            ]
        );

        
4. Refresh the page and test uploading image (in my case using `Files` page in CMS Admin)

_***Note:** You should disable all debug command such as `Debug::show` and `var_dump()`_

**References:**
- [AWS SSL security error : [curl] 60: blablabla](https://stackoverflow.com/questions/24620393/aws-ssl-security-error-curl-60-ssl-certificate-prob-unable-to-get-local?answertab=votes#tab-top)
- [Config to disable SSL](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/faq.html#how-do-i-disable-ssl)
- [Pinging your S3 Bucket Service](https://aws.amazon.com/premiumsupport/knowledge-center/s3-could-not-connect-endpoint-url/)

**Comment by fspringveldt** [comment]
I'm thinking perhaps we could update the documentation for this? Do you
mind raising a PR for this?
